-- 1. Enable PostGIS Extension
CREATE EXTENSION IF NOT EXISTS postgis;

-- 1.5 Create the railway_features table if it doesn't exist
CREATE TABLE IF NOT EXISTS railway_features (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text,
    type text,
    latitude double precision,
    longitude double precision
);

-- 2. Alter Railway Features Table to use Native Geometry
ALTER TABLE railway_features 
ADD COLUMN IF NOT EXISTS geom geometry(Geometry, 4326);

-- 3. Populate Geometry column from existing Lat/Lng (if stored as numeric)
UPDATE railway_features 
SET geom = ST_SetSRID(ST_MakePoint(longitude, latitude), 4326) 
WHERE geom IS NULL;

-- 4. Create a Spatial Index (GiST)
CREATE INDEX IF NOT EXISTS idx_railway_features_geom 
ON railway_features USING GIST (geom);

-- 5. Stored Procedure for Station/Track Radius Detection
CREATE OR REPLACE FUNCTION check_railway_proximity(
    user_lat double precision,
    user_lng double precision,
    radius_meters double precision DEFAULT 100
) 
RETURNS TABLE (
    feature_id bigint,
    feature_name text,
    feature_type text,
    distance_meters double precision
) 
LANGUAGE sql 
AS $$ 
    SELECT 
        id AS feature_id,
        name AS feature_name,
        type AS feature_type,
        ST_Distance(
            geom::geography,
            ST_SetSRID(ST_MakePoint(user_lng, user_lat), 4326)::geography
        ) AS distance_meters
    FROM railway_features
    WHERE ST_DWithin(
        geom::geography,
        ST_SetSRID(ST_MakePoint(user_lng, user_lat), 4326)::geography,
        radius_meters
    )
    ORDER BY distance_meters ASC
    LIMIT 1;
$$;
